/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Proposal } from "./Proposal";
export type { TimeLock } from "./TimeLock";
export type { VoteManager } from "./VoteManager";

export { Proposal__factory } from "./factories/Proposal__factory";
export { TimeLock__factory } from "./factories/TimeLock__factory";
export { VoteManager__factory } from "./factories/VoteManager__factory";
