/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Proposal } from "./Proposal";
export type { VoteManager } from "./VoteManager";

export { Proposal__factory } from "./factories/Proposal__factory";
export { VoteManager__factory } from "./factories/VoteManager__factory";
